modLoader="javafml"
loaderVersion="[26,)" # don't even know if this is used
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/rsttst/kolada/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="kolada" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="$modVersion" #mandatory
 # A display name for the mod
displayName="Kolada" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/RstTst/Kolada" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="Kolada-Logo-Small.png" #optional
# A text field displayed in the mod UI
#credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="RstTst" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Kotlin Language Adapter for Minecraft Forge (MC version 1.14.4).

Information for developers available on GitHub: https://github.com/RstTst/Kolada
License information at: https://github.com/RstTst/Kolada/blob/master/license/README.md

For MC version 1.8.4 or below refer to Shadowfacts' Forgelin (https://www.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin/)
'''
[[dependencies.kolada]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[26,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.kolada]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"